name: PublishDockerImage

on:
  release:
    types: [published]

jobs:
  generate:
    name: 'Update node-red-docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Check out node-red repository
        uses: actions/checkout@v2
        with:
            path: 'node-red'
      - name: Check out node-red-docker repository
        uses: actions/checkout@v2
        with:
            repository: 'node-red/node-red-docker'
            path: 'node-red-docker'
      - uses: actions/setup-node@v1
        with:
            node-version: '12'
      - run: node ./node-red/.github/scripts/update-node-red-docker.js
        id: updateFiles
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.NR_REPO_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          path: 'node-red-docker'
          title: '[TEST] Update to Node-RED ${{ env.newVersion }} release'
          body: |
            Updates the Node-RED Docker repo for the ${{ env.newVersion }} release.

            This PR was auto-generated by a GitHub Action. Any questions, speak to @knolleary
